package se.anders.tunerstudio.aetuner.guided.method;

import se.anders.tunerstudio.aetuner.guided.GuidedTaskFocusCatalog;
import se.anders.tunerstudio.aetuner.guided.GuidedTuningRecipe;
import se.anders.tunerstudio.aetuner.model.AeProjectSnapshot;
import se.anders.tunerstudio.aetuner.model.ChannelRole;
import se.anders.tunerstudio.aetuner.model.LiveSample;

/**
 * UX/product scaffold for a known current EpicEFI AE task whose tuning engine
 * has not been implemented yet. It deliberately owns no capture or write path.
 */
public final class PlannedGuidedTaskModule implements GuidedAeMethodModule {
    private final GuidedTuningRecipe recipe;

    public PlannedGuidedTaskModule(GuidedTuningRecipe recipe) {
        if (recipe == null || recipe.implemented) {
            throw new IllegalArgumentException("PlannedGuidedTaskModule requires a planned recipe");
        }
        this.recipe = recipe;
    }

    @Override public GuidedTuningRecipe recipe() { return recipe; }
    @Override public CaptureMode captureMode() { return CaptureMode.ARCHITECTURE_ONLY; }
    @Override public String setupTitle() { return recipe.displayName; }
    @Override public String setupGuidance() { return recipe.guidance; }
    @Override public String captureGoal() {
        return "Planned Guided task. No validated live-capture/tuning engine is attached yet.";
    }
    @Override public ChannelRole[] requiredRoles() { return new ChannelRole[0]; }
    @Override public ChannelRole[] contextRoles() { return new ChannelRole[0]; }
    @Override public String operatorInputs(AeProjectSnapshot snapshot) {
        return "Use Guided Focus to review the intended controls, operator procedure, evidence quality rules and next dependency. Numerical tuning is intentionally withheld until implemented.";
    }
    @Override public String accumulationPlan() {
        return "No evidence is accumulated by this scaffold yet. Future capture must be task-specific rather than reusing an unrelated method merely to make the UI look active.";
    }
    @Override public String reviewOutputs() {
        return "UX/product guidance only. No recommendation, ProposalWritePlan or Apply authority is generated by this scaffold.";
    }
    @Override public String currentTuneContext(AeProjectSnapshot snapshot) {
        String broad = snapshot == null
                ? "Working tune not read yet."
                : snapshot.methodStatusText();
        return broad + "\nKnown current controls for this task: "
                + GuidedTaskFocusCatalog.controlsText(recipe)
                + "\nIndividual values not already present in AeProjectSnapshot will be added when this task becomes an active implementation slice.";
    }
    @Override public boolean activityObserved(LiveSample sample) { return false; }
}
